# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Blaklinten-WEB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Gets access to source code
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        # python -m venv venv  creates a virtual environment
        # source venv/bin/activate activates the virtual environment
        run: |
          python -m venv venv 
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

      - name: Uploads Code as an artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          # . uploads the entire repo
          # !venv/ excludes the virtual environment
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # gets the deploy-to-webapp job output url and shows the url in github actions workflow
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: . # This downloads the entire repo

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "Blaklinten"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE }}
